import type { QuestionSetDefinition } from "./question-set";

export const STATEMENT_DEFAULT_QUESTION_SET_V1: QuestionSetDefinition = {
  version: "1.0.0",
  code: "STATEMENT_DEFAULT_V1",
  title: "진술서 기본 질문셋",
  description: "진술서 초안 생성을 위한 기본 인터뷰 질문셋",
  status: "PUBLISHED",
  supportedDocumentTypes: ["STATEMENT"],
  visibleToRoles: ["ADMIN", "LAWYER", "STAFF", "CLIENT"],
  sections: [
    {
      key: "basic",
      title: "기본 정보",
      order: 0,
      questions: [
        {
          key: "incident_date",
          title: "사건 발생일은 언제입니까?",
          inputType: "DATE",
          category: "BASIC_INFO",
          visibility: "ALL",
          required: true,
          order: 0,
          paragraphMappings: [
            {
              documentType: "STATEMENT",
              templateSectionKey: "incident_overview",
              paragraphKey: "incident_date_summary",
              transform: "RAW",
              required: true,
              weight: 1,
            },
          ],
          options: [],
          conditions: [],
          tags: ["날짜", "핵심"],
        },
        {
          key: "incident_place",
          title: "사건 발생 장소는 어디입니까?",
          inputType: "SHORT_TEXT",
          category: "BASIC_INFO",
          visibility: "ALL",
          required: true,
          order: 1,
          paragraphMappings: [
            {
              documentType: "STATEMENT",
              templateSectionKey: "incident_overview",
              paragraphKey: "incident_place_summary",
              transform: "RAW",
              required: true,
              weight: 1,
            },
          ],
          options: [],
          conditions: [],
          tags: ["장소"],
        },
      ],
    },
    {
      key: "fact",
      title: "사실관계",
      order: 1,
      questions: [
        {
          key: "incident_timeline",
          title: "사건 경위를 시간순으로 자세히 작성해 주세요.",
          inputType: "LONG_TEXT",
          category: "TIMELINE",
          visibility: "ALL",
          required: true,
          order: 0,
          paragraphMappings: [
            {
              documentType: "STATEMENT",
              templateSectionKey: "fact_description",
              paragraphKey: "timeline_summary",
              transform: "TIMELINE_SUMMARY",
              required: true,
              weight: 1,
            },
          ],
          options: [],
          conditions: [],
          tags: ["경위", "타임라인"],
        },
        {
          key: "has_witness",
          title: "목격자가 있습니까?",
          inputType: "BOOLEAN",
          category: "EVIDENCE",
          visibility: "ALL",
          required: true,
          order: 1,
          options: [],
          conditions: [],
          paragraphMappings: [],
          tags: ["증인"],
        },
        {
          key: "witness_detail",
          title: "목격자 정보와 진술 내용을 적어 주세요.",
          inputType: "LONG_TEXT",
          category: "EVIDENCE",
          visibility: "ALL",
          required: false,
          order: 2,
          conditions: [
            {
              sourceQuestionKey: "has_witness",
              operator: "IS_TRUE",
            },
          ],
          paragraphMappings: [
            {
              documentType: "STATEMENT",
              templateSectionKey: "evidence",
              paragraphKey: "witness_summary",
              transform: "JOIN_LINES",
              required: false,
              weight: 0.8,
            },
          ],
          options: [],
          tags: ["증인", "증거"],
        },
      ],
    },
  ],
};
